version: '3.8'
services:
  async-web:
    build: .
    image: async-web
    container_name: async-web
    environment:
      AZURE_SERVICE_BUS_HOST: ${AZURE_SERVICE_BUS_HOST}
      AZURE_SERVICE_BUS_USERNAME: ${AZURE_SERVICE_BUS_USERNAME}
      AZURE_SERVICE_BUS_PASSWORD: ${AZURE_SERVICE_BUS_PASSWORD}
      AZURE_SERVICE_BUS_QUEUE: ${AZURE_SERVICE_BUS_QUEUE}
      AZURE_SERVICE_BUS_SESSION_QUEUE: ${AZURE_SERVICE_BUS_SESSION_QUEUE}
